### PR TITLE
Fixed: update drag method and move logic into encumber.rb

### PR DESCRIPTION
**Pull request by william57m**
The drag event is now done in encumber.rb and do the following serie of actions : mouse down > mouse mouve > mouse up, instead of have this logic in Cappuccino which achieved the drag'n'drop instantly.

### CODE REVIEW

**Comment by Dogild** [comment]
The encumber part seems good to me.

However, the cappuccino part needs to be improved.
It's good to have the method `simulateMouseUpOnPoint` and `simulateMouseDownOnPoint`. The methods `simulate*Click` should use these methods.

Can we get rid of `_perfomMouseEventOnPoint:(CGPoint)locationWindowPoint toPoint:(CPView)locationWindowPoint2 window:(CPWindow)currentWindow eventType:(unsigned)anEventType numberOfClick:(int)numberOfClick modifierFlags:(CPArray)flags` ? This method was mainly created to simulate the drag event.

**Comment by william57m** [comment]
Ok, I dropped all the drag'n'drop methods from Cucumber.j and I created new methods to simulate mouse up and mouse down which are now used in the Cucapp Recorder instead of the all in one drag'n'drop methods.
To have the same behaviors between the Recorder and Cucapp features, I also added the mouse up and mouse down methods to encumber.rb.
I also removed the useless code and simplify the `_perfomMouseEventOnPoint:(CGPoint)locationWindowPoint toPoint:(CPView)locationWindowPoint2 window:(CPWindow)currentWindow eventType:(unsigned)anEventType numberOfClick:(int)numberOfClick modifierFlags:(CPArray)flags`

**Comment by Dogild** [comment]
You need to sync with the master, there are conflicts that mus be resolved

**Comment by william57m** [comment]
Ok it's good.

**Pull request closed without merging**
